import { requireImage } from '../webpack-require';

var description = '';

var stories = [
  {
    id:1,
    title:'Tung Shing, a Chinese divination guide and almanac',
    name:'Cheung',
    image:'tungshing.jpg',
    filter:['SREA'],
    story: `Sometimes things are out of our control. I used to be a designer in Guangzhou (a city in China). I had a decent and stable income back then, I could even travel to different places for work and didn't have to pay out of the pocket. However, things were never the same when I was unwell and went to see a 96-year-old "Granny" in a village who was a fortune-teller. She told me, "in mid-summer next year, you will go all the way to the West, and that trip will be a long one that crosses half of the globe". I didn't even know what "mid-summer" means at that time, but all I knew was that I ended up migrating to the UK (London) in the summer the following year. My husband is a British Chinese, and there's a Chinese slang "follow the rooster if you marry a rooster, follow the dog if you marry a dog. I have been living here for more than 30 years now, this is my home, my family is here, my sons are here, I can't go back anymore. I am not trying to say that I believe in fatalism, yet sometimes it is hard not to believe in fate. When my sister-in-law's mum passed away, we all went to the hospital. At that time, I wasn't sure if I was contaminated with some "dirty stuff" (a Chinese saying when someone encountered ghosts), my sister-in-law and I both realised our temples were darkened. When I went home, I immediately jumped across a fire bowl and showered with pomelo leaves. She did not perform the rituals, and later she developed depression which she is trying to maintain her wellbeing through exercise now. You may think I am superstitious, but I think there is a reason and value behind why Chinese Feng Shui and Tung Shing are being seen as intangible cultural heritage. 
有些事情是身不由己的。我本來在廣州是一個收入穩定的設計師，間中還能借出差用公費去旅行。但是有年我身體不舒服，找了一個96歲的算命婆婆，她跟我說：“你明年仲夏會一路向西，半個地球走“。 我那時候還不知道什麼叫仲夏呢，第二年的夏天就真的移民來倫敦了。老公是華僑，嫁雞隨雞嫁狗隨狗嘛。 現在來了已經三十多年， 家在這裡，兒子也在，也回不去了。不是說我唯命論什麼的，但有時候真的很難不相信。我弟婦的媽媽去世時，我們都去了醫院。那個時候不知是否沾了髒東西（”污糟野“），當時我和弟婦兩個印堂發黑，我回家後立刻跨火盆，用碌柚葉 （柚子葉）洗澡。我弟婦卻沒做，結果後來得了抑鬱症，現在要靠做運動維持健康。你可能覺得我迷信，但是中國的風水學，通勝等被視為文化遺產，我認為並非不無道理.`,
  },
  {
    id: 2,
    title:'A 5-pound note',
    name:'anonymous',
    image:'5pound.jpg',
    filter:['SREA'],
    story:`I actually did not come via the plane, contrary to many others in the community centre. I came on a cruise and it took a month to get here from Hong Kong. It's actually not too bad - I came via Cape Town. I could still remember at that time in Cape Town the bus was divided into Black people and White people and I didn't know where to sit. It has been almost 60 years since I first arrived in 1960. He came in 1958, that was even earlier, and his ship passed through Marseilles. We came to the UK to earn a living, I remember they were recruiting healthcare professionals, and after we arrived we have been working in a hospital since. Life was tough at that time, you younger generation has a much easier life than us. Other people could get £5.5 a week, but we could only get £5 a month after deducting our pay for food and rent. 

我當年是坐郵輪來的，坐了整整一個月，其實也挺不錯的，途徑好望角。我還記得那時候南非的種族隔離政策，公交上黑人白人不能混坐，而我也不知道該坐哪邊。1960年到現在，已經快六十年了。 他是五八年來的，比我還早，他的船途徑馬賽。我們來英國是為了謀生，一直在醫院工作。那時候生活艱難，你們現在比我們輕鬆多了。別人一周拿到5.5鎊的工資，而我們扣掉伙食費和住宿費以後，一個月只有五鎊。 

Note: the object was chosen by the curator as the storyteller didn’t mention any significant object.`
  },
{
    id: 3,
    title:'Multiplication table',
    name:'anonymous',
    image:'multiplicationtable.jpg',
    filter:['SREA'],
    story:`When I went to school in Hong Kong, we were forced to memorise multiplication tables. I remember reciting, 3 times 3 is 9, 8 times 7 is 56. And I really never understood what I was reciting, until I came to the UK. Here, schools use objects to show students the arithmetic. This felt so different to me, and I finally understood what I had been reciting for so many years, because I could see it. But I’ve heard that the British education is starting learn from the Chinese way and make students do more rote learning too. 
當我在香港讀書時，我們被迫記住乘數表。我記得背誦，3乘3是9，8乘7是56。在我來到英國之前，我真的不明白我在背誦什麼。在這裡，學校使用實物向學生展示算術。這對我來說感覺完全不同，我終於明白到我多年來背誦的東西，現在我能看到它。但我聽說英國的教育開始學習中國的方式，讓學生做更多的死記硬背.`
  },
{
    id: 4,
    title:'Kite',
    name:'Cheung',
    image:'kite.jpg',
    filter:['SREA'],
    story:`I chose to stay in the UK for my son. It’s been almost 20 years now. I came here first on my own, then my son also came over. As a single mum, it’s hard. While he was growing up, I had to work long hours to support him and I had no friends for more than 15 years. It’s great now that he is in university, and I finally feel like all my hard work has paid off. I am not going back to Hong Kong, and my son doesn’t want to return to Hong Kong either. When he was young, I would threaten that if he didn’t behave or study, I would send him back to his grandma’s place in Hong Kong. Perhaps that is why he doesn’t want to go back there anymore. But we do miss the food there and sometimes we go back to Hong Kong to eat. 
Raising children is like flying kites. They can fly up high and achieve great things, but I will always hold the handle.  I know I will never let him go.  

我選擇留在英國是為了我的兒子。現在差不多已經20年了。我先是自己來到這裡，然後我的兒子也來了。作為一個單身的媽媽，這很難。在他成長的過程中，我不得不長時間工作來支持他，而我15年來沒有朋友。現在他在大學裡成績非常好，我終於覺得我的辛勤工作没有白費。我不會回香港，我的兒子也不想回香港。在他還小的時候，我會威脅他說，如果他表現或讀書不好，我會把他送回香港和奶奶一起居住。也許這就是因為他不想再回到那裡去，所以就很努力讀書。但我們確實想念香港的美食，有時間我們會回香港品嘗一下家鄉的食物。
撫養孩子就像放風箏一樣。他們可以飛得很高並且能夠實現偉大的目標和夢想，但我會永遠抓住它，我不會讓他離開.`
  },
  {
    id: 5,
    title:'Chinese Independent School of Tower Hamlets',
    name:'Choi and Cheung',
    image:'school.jpg',
    filter:['SREA'],
    story:`Choi: You have to be able to control your children, at least while they are young and are still subject to your control. I have two daughters, aged 9 and 5. My daughter is already the least busy compared to the children of my friends. She is 9 and she only has skating, piano, singing and Cantonese and Mandarin class to attend. I am quite relaxed about the piano classes. I don’t need my children to go for music exams if they don’t want to. But Chinese classes are non-negotiable. They need to learn Chinese. Their grandparents and great-grandparents in Malaysia don’t speak English so it’s important for them to learn Chinese so that they can communicate with them. 
Will you push your kids? If you don’t push them, they may regret that you did not push them when they grow up. 
Cheung: My son is very stubborn. He doesn’t like to act under my control or follow what I’ve set out for him.  At first, I parented him like how a typical Hong Kong parent would. I was strict with him and would make sure he did his homework right after coming home from school. But nowadays, I have learnt from the parenting attitudes and styles here and have become more relaxed. Education here has a different kind of focus. For example, I heard from my friend that at her daughter’s nursery school, they would spend long hours doing gardening and other activities instead of focusing on academic skills. This is quite different from nursery schools in Hong Kong. I think that it is important that we integrate ideas from other cultures while keeping some of our own. This is what Chinese people have been good at throughout history. We integrate ideas. We are less aggressive. I think that Chinese children do tend to perform better in school, but they are also less self-motivated learners. You don’t see that many Chinese people making new inventions or big scientific discoveries, and I think that this is related to how Chinese children are educated.  Here in the UK, children are more self-driven, pursue their ideas on their own, and learn research methods. 
One thing that has been hard for me to accept is how my children have used what they have learnt in school to go against me. Here, children are taught to stand up for their rights, and it is harder for parents to control them, especially as they get older. It’s easier when they are young. You know, in Chinese culture we sometimes hit our children when they don’t listen to us, but here they will say, “mum, that’s abuse!” 
蔡：你必須能夠控制你的孩子，至少在他們年輕的時候仍然受你的控制。我有兩個女兒，分別是9歲和5歲。與朋友的孩子相比，我的女兒已經是最不忙的了。她9歲，她只有滑冰，鋼琴，唱歌，粵語和普通話課。關於鋼琴課，我不會太緊張。如果她們不想，我不需要我的孩子去參加音樂考試。但中文的課程是不容談判的。她們需要學習中文。他們在馬來西亞的祖父母和曾祖父母不會說英語，所以學習中文對她們來說很重要。
你會給你的孩子在讀書上有壓力嗎？如果你不給你的孩子在讀書上有壓力，他們可能會在他們長大後，怨你沒有給他們嚴厲一點。

張：我兒子很固執。他不喜歡在我的控制下行事或遵循我為他規定的要求。一開始，我像一個典型的香港父母那樣對他很嚴格。我對他有嚴格要求，並確保放學回家後他得馬上把功課做完。但是現在，我從這裡的育兒態度和風格中學到了東西，變得更加寬鬆。這裡的教育有不同的側重點。例如，我從朋友那裡聽說，她女兒的托兒所，他們會花很長時間從事園藝和其他活動，而不是專注於學術技能。這與香港的托兒所完全不同。我認為，重要的是我們要整合來自不同文化的想法，最要緊要保留我們自己的一些優良文化。這是中國人歷史上擅長的。我們整合了想法後覺得我們沒其他人那般激進。我認為中國孩子在學校的表現往往很好，但他們是不那麼自主學習的。你沒有看到很多中國人有新發明或科學創新，我認為這與中國兒童的教育方式有關。在英國，孩子們更加自主動，自己追求自己的想法，並學習研究方法。
我很難接受的一件事是我的孩子利用他們在學校學到的東西來反駁我。在這裡，孩子們被教導要維護他們的權利，父母更難控制他們，特別是隨著年齡的增長。你知道的，在中國文化中，我們有時會在不聽話的時候，我們會體罰我們的孩子，但在這裡他們會說，“媽媽，那是虐待！”`
  },
  {
    id: 6,
    title:'China Town',
    name:'Choi',
    image:'chinatown.jpg',
    filter:['SREA'],
    story:`You can’t taste traditional Chinese flavours here. Even if we use the same ingredients, they taste different because of where they come from. Sometimes, when I miss traditional Chinese food, I will search for recipes online and make them myself. But I have also learnt to adapt to the flavours and cooking styles here. In the past, I would go to Chinatown to eat Chinese food, even though I knew it wouldn’t taste as good as what I remembered from home.  But I seldom go to Chinatown now. It has changed since I first came here, that was more than 20 years ago. Some “cha chan tengs” (茶餐廳, Hong Kong-style canteens) that I used to like to visit when I was younger have now closed down. Back in the 70s, shops in Chinatown were mainly owned by people from the New Territories in HK, where I am from. Since the 1980s, this has changed. Many Vietnamese came, and more and more people from Malaysia and Mainland China started to move here as well. Nowadays, when I walk around Chinatown, I see Japanese restaurants, dessert stores and bubble tea shops, but these were not things I grew up with or food I would want to eat. It seems like the things that represent the memories from our generation are missing, or are fading away in the modern Chinatown. 
你不能在這裡品嚐到中國食物的傳統風味。即使我們使用相同的成分，它們的味道怎麼也有不同，因為它們的材料來自不同地方。有時，當我想念傳統的中國食物時，我會在網上搜索食譜並自己製作。但我也學會了適應這裡的風味和烹飪風格。在過去，我會去唐人街吃中國菜，儘管我知道它的味道不如我記憶中的那麼好。但我現在很少去唐人街吃東西。自從我第一次來到這裡以來已經發生了變化，這是20多年前的事了。在我年輕的時候，我常常想去的一些“茶餐廳”（茶館，香港式餐館），但現在已經倒閉了。早在70年代，唐人街的商店主要由來自香港新界的人士經營。自20世紀80年代以來，情況發生了變化。許多越南人來了，越來越多來自馬來西亞和中國內地的人也開始搬到這裡。如今，當我走遍唐人街時，我會看到日本餐館，甜品店和珍珠奶茶館，但這些不是隨我我長大的東西，也不是我想吃的食物。 似乎代表我們這一代人記憶的東西在現代唐人街消失了，或者正在逐漸消失中。`
  },
  {
    id: 7,
    title:'Orange juice',
    name:'Toan',
    image:'juice.jpg',
    filter:['SREA'],
    story:`I have been in the UK for 35 years. I was 5 when I came. I came to the UK with my middle sister and mother by plane to meet my dad and my older sister. I wish I could remember much about Vietnam but I couldn’t. The thought of visiting Vietnam for the first time the coming Christmas is an apprehensive feeling. If I had lots of family members there, I would feel more connected. But it’s still my home. It’ s important to know where you come from. When I was young, I just thought about fitting in and learning English, but as you get older, you realise you can’t ignore who you are. It’s just made it a lot richer. I do struggle with my identity, but I am getting there, I am closer, closer to acceptance, more than ever. 
As a kid, I loved orange juice. However, we couldn’t afford it in Vietnam. When I got on the plane to the UK as a five-year-old, I saw the orange juice, it was the kind that was sealed up with a foil on top. It was amazing, I really wanted to drink it, but I wanted to give something to my sister who was in the UK already, even though she’s someone whom I couldn’t remember. I had to resist my urge to drink it on the whole plane journey. When I met her at the station, I gave it to her and she said, “Oh, that’s really sweet”. And then I realised that orange juice was quite common here. And that was me, a five-year-old, who desperately wanted to have it. So yeah, that sums up the transition. 
I used to own a restaurant, but I sold it eight months ago. I had no idea what I wanted to do next, but I wanted to be helpful in some way. I am volunteering at Citizens Advice Bureau and figuring out my path. I met someone recently, an Iraqi. He’s been here for four years as an asylum seeker. Hearing his story is really interesting actually. I thought a person would apply for refugee status, and then eventually they will get settled. That’s what I’ve been told. So, I was like, that’s all very straightforward. However, he said, “well, I am an asylum seeker applying for refugee status, but it hasn’t happened. I have been stuck in this no man’s land for four years where I can’t work because I’ve got no paperwork.” I am not very clued up with issues regarding refugees nowadays. In a way, the idea of myself being from a refugee background has been boxed in my head. I have to some extent put this to the side a bit, and I am not personally ready to explore that side yet at the moment. I am excited about the culture and history of Vietnam, but I haven’t focused on the refugee side of my life yet. That’s kind of being compartmentalised. 
When I experienced difficult stuff when I was younger, therapy has been valuable to me and has helped me massively. I say to my friends who are my age that there’s nothing to be ashamed of get help. But turn it around, it’s almost impossible to say this to my parents. A mutual friend at law school who’s Chinese bought a therapy session for her mum as a birthday present, and she went crazy about it. 

Tôi đã ở Anh được 35 năm. Tôi sang đây lúc năm tuổi. Tôi đến Anh cùng chị ba và mẹ bằng máy bay để gặp ba và chị hai. Tôi ước mình có thể nhớ nhiều hơn về Việt Nam nhưng tôi không thể. Ý nghĩ đến thăm Việt Nam lần đầu tiên vào Giáng sinh sắp tới cho tôi cảm giác lo lắng. Nếu tôi có nhiều người thân ở đó, tôi sẽ cảm thấy kết nối nhiều hơn. Nhưng đó vẫn là quê hương tôi. Việc biết bạn đến từ đâu là quan trọng. Khi tôi còn trẻ, tôi chỉ nghĩ đến việc hòa nhập và học tiếng Anh, nhưng khi bạn già đi, bạn nhận ra rằng bạn không thể lờ đi câu hỏi bạn là ai. Nó cứ tích tụ ngày càng nhiều lên. Tôi đã phải đấu tranh với việc tìm ra danh tính của mình, nhưng tôi đang đi đến đích, tôi đang đến gần hơn, gần hơn với sự chấp nhận, hơn bao giờ hết.

Khi còn bé, tôi rất thích nước cam. Tuy nhiên, chúng tôi không thể mua nó ở Việt Nam. Khi tôi lên máy bay tới Anh Quốc lúc năm tuổi, tôi đã thấy nước cam, loại được dán kín với một lớp giấy bạc trên cùng. Thật tuyệt vời, tôi đã rất muốn uống nó, nhưng tôi muốn tặng một thứ gì đó cho chị gái tôi ở Anh, mặc dù lúc ấy tôi không thể nhớ được chị ấy thế nào. Tôi đã phải chống lại sự thôi thúc muốn uống nó trên suốt chuyến bay. Khi tôi gặp chị ở nhà ga, tôi đã đưa nó cho chị và chị ấy nói, “Em thật ngọt ngào”. Sau này, tôi nhận ra nước cam khá phổ biến ở đây. Trong khi đó, tôi, một đứa trẻ năm tuổi, đã khao khát muốn uống nó. Vì vậy, đúng thế, vật này đã tóm lại cả quá trình của sự thay đổi.

Tôi đã từng mở một nhà hàng, nhưng tôi đã bán nó 8 tháng trước. Tôi không biết tôi muốn làm gì tiếp theo, nhưng tôi muốn mình có ích theo một cách nào đó. Tôi tình nguyện tại Văn phòng Tư vấn Công dân và tự tìm ra con đường của mình. Gần đây, tôi đã gặp một người I-rắc. Anh ấy đã ở đây bốn năm với tư cách là người xin tị nạn. Thực sự thú vị khi nghe câu chuyện của anh ấy. Tôi đã nghĩ rồi một người nộp đơn xin tị nạn cũng sẽ được định cư. Đó là những gì tôi được kể. Vì vậy, tôi đã cho rằng mọi thứ rất đơn giản. Tuy nhiên, anh ấy nói “tôi là một người tị nạn xin tị nạn, nhưng điều đó vẫn chưa xảy ra. Tôi đã bị mắc kẹt ở chốn không lối thoát này bốn năm, nơi tôi không thể làm việc vì không có giấy tờ.” Tôi hiện không hiểu lắm về các vấn đề liên quan đến người tị nạn. Ở một khía cạnh, ý nghĩ về bản thân mình cũng là một người tị nạn đã chôn giấu trong đầu tôi. Tôi phải, ở một mức độ nào đó, đặt nó sang một phía, và cá nhân tôi chưa sẵn sàng để khám phá phía đấy vào lúc này. Tôi rất thích thú văn hóa và lịch sử Việt Nam, nhưng tôi vẫn chưa tập trung vào khía cạnh tị nạn của cuộc đời mình. Hình dung như tôi muốn ngăn cách nó vậy.

Khi tôi trải qua những khó khăn thời trẻ, trị liệu rất đáng giá với tôi và giúp ích tôi rất nhiều. Tôi nói với những người bạn bằng tuổi tôi rằng không có gì phải xấu hổ khi tìm sự giúp đỡ. Nhưng ngược lại, tôi gần như không thể nói điều này với bố mẹ tôi. Một người bạn học chung trường luật với tôi, người Trung Quốc đã mua một buổi trị liệu cho mẹ làm quà sinh nhật và mẹ cô ấy đã nổi điên vì điều đó.`
  },
  {
    id: 8,
    title:'A Jacket',
    name:'Captain Ho',
    image:'captainjacket.jpg',
    filter:['SREA'],
    story:`During the course of my struggles before and when I decided to leave the country, I still carry these objects that reflect my home, as well as the sentiments towards it. For the past number of years, they have reminded me of the difficult times, the struggles, and the oppression of the country I left behind. They also remind to not be complacent, not ignoring the past; using these difficult times, struggling times to create a foundation to be positive for my future. For example, I am having a dinner, It doesn’t matter whether it’s meat, fish or something, but I am having a dinner, compared to years ago I wouldn’t be able to have that. My relationship with these objects has always stayed the same, and they will always be for the rest of my life. I will never throw them away.
They have always motivated me to strive to do things better. One of the reasons why I switched from working in housing to mental health was that I have seen people having mental health issues in my previous work, and I wonder if I could use my skills to get involved in the mental health field. The word “mental health” is not existent in our dictionary; it’s very unknown to people. When people suffer from some form of issues, they believe that's okay, or that could be because of the karma or something you've done in the past; having been possessed by evil spirits. Seeking help from health professionals isn’t their first step. They may try some sort of herbal medication, go to the temple or something. By the time they are seen by health professionals, it’s probably the latest phase and the matter could become very serious. They think, “I am taking medication, I have seen my doctor, it’s not a problem”. But it’s a problem and they don’t recognize it. They think they are 60, 70 [years old], and suffering from diabetes is an obvious thing*.
I keep and use the objects to pass on the experience and what I have had, so the younger generations, my children, my grandchildren would be able to understand what I have been through. In community work, legacy doesn't mean that you're doing that for the sake of this project, and then have it sitting on the shelf dusting away. Prolonging or maintaining it requires commitment, willingness and being creative as well. Who else is going to replace you? Do you have the ability to do capacity building?

One issue is that the representation of our community is very small compared to other BME groups, and it lacks both professionals coming from the community for the voices to be heard, as well as an and the lack of awareness of the culture. The arrival of the Vietnamese and the Vietnamese- Chinese communities only began around the period of 1979, but other communities such as the Indian subcontinent, the Caribbean, the Irish and the Jews have been here year-on-year.  They do have prominent figures sitting or working in the government, doctors, lawyers etc. In my work as an Independent Mental Health Advocate, I am also a cultural advisor to raise awareness about the culture. In the health sector, you can count on your hands the number of Vietnamese GP, or counsellors in the UK.
Moreover, you have to bear in mind, the community here in the UK is totally different from the community in Vietnam. The reason why people coming to the UK in the first place was because they were fleeing from the country because of oppression and torture, either politically or economically. The families wanted the children to do well rather than community work. People in Vietnam have never heard of the word social work, or community worker. 

Yes, there are some activities more or less associated with community and youth like Scouts, but that’s purely for pleasure or on a voluntary basis. The younger generation are trying to do what they expected to do, or they are under influences from Western culture. Some of them may see themselves as a Westerner, or do not want to be associated with being Vietnamese, “too noisy, too much hassle. I’d rather do something else”. I have to appreciate that from this culture, the Western culture, when health professionals retire, they use their knowledge and skill to do volunteer work. For the Vietnamese community, I believe, everything you do, it’s about money, money, money. We need to break that. Change has to come from within the family within the generation and the community.

*Note: Captiain Ho: “When I carried out the questionnaire survey, I noticed that many elderly people stated their physical health are ok, contradicted to the section about their physical and mental health problem which they have listed a number of illness.”
Trong suốt quá trình tôi đấu tranh trước và khi tôi quyết định rời khỏi Tổ quốc, tôi vẫn mang theo những đồ vật này bởi chúng phản chiếu hình ảnh nhà của tôi, cũng như tình cảm của tôi đối với nó. Trong nhiều năm qua, chúng đã gợi tôi nhớ về thời kỳ khó khăn, cuộc đấu tranh và sự áp bức của đất nước mà tôi đã bỏ lại phía sau. Chúng cũng nhắc nhở tôi đừng tự mãn, đừng gạt bỏ quá khứ; hãy sử dụng những thời điểm khó khăn này, thời gian đấu tranh ấy để tạo một nền tảng tích cực cho tương lai của tôi. Ví dụ, tôi đang dùng bữa tối, không quan trọng nếu đó là thịt, cá hay thứ gì đó, nhưng tôi đang ăn tối, so với những năm trước tôi sẽ không thể có được điều đó. Mối quan hệ của tôi với những đồ vật này luôn như một, và chúng sẽ luôn ở bên tôi suốt cuộc đời. Tôi sẽ không bao giờ ném chúng đi.
Chúng luôn thúc đẩy tôi phấn đấu để làm mọi thứ tốt hơn. Một trong những lý do khiến tôi chuyển từ công việc về nhà ở sang sức khỏe tâm thần là vì tôi đã thấy những người có vấn đề về tâm thần trong công việc trước đây của tôi và tôi tự hỏi liệu tôi có thể sử dụng các kỹ năng của mình để tham gia vào lĩnh vực tâm thần hay không. Từ “sức khỏe tâm thần”, không có trong từ điển của chúng tôi; Rất ít người biết đến nó. Khi mọi người gặp phải một số vấn đề, họ tin rằng họ không sao, hoặc đó có thể là do nghiệp chướng hoặc điều gì đó bạn đã làm trong quá khứ; hay bị quỷ ám. Tìm kiếm sự giúp đỡ từ các chuyên gia y tế không phải là bước đầu tiên của họ. Họ có thể thử một số loại thuốc thảo dược, đi chùa hoặc làm một cái gì đó. Thời điểm họ tìm đến các chuyên gia y tế có lẽ là bước cuối cùng và vấn đề có thể trở nên rất nghiêm trọng. Họ nghĩ rằng, “tôi đang dùng thuốc, tôi đã gặp bác sĩ, không có vấn đề gì cả”. Nhưng đây là một vấn đề và họ không nhận ra nó. Họ nghĩ rằng họ 60, 70 [tuổi], và mắc bệnh tiểu đường là một điều hiển nhiên*.
Tôi giữ và dùng những đồ vật này để truyền lại kinh nghiệm và những gì tôi đã có, để các thế hệ trẻ, con cái, và cháu của tôi sẽ có thể hiểu những gì tôi đã trải qua. Trong công việc cộng đồng, di sản để lại không có nghĩa là bạn đang làm điều đó vì lợi ích của dự án này, và sau này để nó đứng trên kệ đầy bụi. Việc kéo dài hoặc duy trì nó đòi hỏi sự cam kết, sự sẵn lòng và sáng tạo cũng vậy. Ai sẽ thay thế bạn? Bạn có khả năng xây dựng năng lực không?
Một vấn đề là đại diện của cộng đồng chúng tôi rất nhỏ so với các nhóm BME khác và nó thiếu cả các chuyên gia đến từ cộng đồng để có tiếng nói, cũng như thiếu nhận thức về văn hóa. Sự xuất hiện của cộng đồng người Việt và người Việt - Trung chỉ bắt đầu vào khoảng năm 1979, nhưng các cộng đồng khác như tiểu lục địa Ấn Độ, Caribbean, Ailen và Do Thái đã ở đây nhiều năm. Họ có những nhân vật nổi bật đang ngồi hoặc làm việc trong chính phủ, bác sĩ, luật sư, v.v. Trong công việc của tôi với tư cách là một người tư vấn sức khỏe tâm thần độc lập, tôi cũng là một cố vấn văn hóa để nâng cao nhận thức về văn hóa. Trong lĩnh vực y tế, bạn có thể đếm trên ngón tay số lượng bác sĩ đa khoa hoặc nhân viên tư vấn người Việt tại Vương quốc Anh.
Hơn nữa, bạn phải nhớ rằng, cộng đồng (người Việt) ở Anh hoàn toàn khác với cộng đồng ở Việt Nam. Lý do tại sao mọi người đến Vương quốc Anh ngay từ đầu là vì họ chạy trốn khỏi đất nước vì bị áp bức và tra tấn, cả về chính trị hoặc kinh tế. Các gia đình muốn các con làm tốt hơn là chỉ làm công việc cộng đồng. Người dân ở Việt Nam chưa bao giờ nghe đến từ công tác xã hội, hay nhân viên cộng đồng. Phải, có một số hoạt động ít nhiều gắn liền với cộng đồng và thanh niên như Hướng đạo sinh, nhưng đó hoàn toàn là vì niềm vui hoặc trên cơ sở tự nguyện. Thế hệ trẻ đang cố gắng làm những gì họ mong muốn làm, hoặc họ chịu ảnh hưởng từ văn hóa phương Tây. Một số người trong số họ có thể xem mình là người Tây, hoặc không muốn liên quan đến việc là người Việt Nam, “quá ồn ào, quá nhiều rắc rối. Tôi muốn làm một cái gì đó khác”. Tôi phải đánh giá cao rằng từ văn hóa này, văn hóa phương Tây, khi các chuyên gia y tế nghỉ hưu, họ sử dụng kiến thức và kỹ năng của họ để làm công việc tình nguyện. Đối với cộng đồng người Việt, tôi tin rằng, tất cả những gì bạn làm, đó là về tiền, tiền, tiền. Chúng ta cần phá vỡ điều đó. Thay đổi phải đến từ gia đình trong thế hệ và cộng đồng này.

* Lưu ý: Thuyền trưởng Ho: Khi tôi thực hiện phiếu câu hỏi khảo sát, tôi nhận thấy rằng nhiều người cao tuổi cho biết sức khỏe thể chất của họ vẫn ổn, mâu thuẫn với phần về vấn đề sức khỏe thể chất và tinh thần của họ mà họ đã liệt kê một số bệnh.`
  },
  {
    id: 9,
    title:'White Flower Oil',
    name:'Donna',
    image:'oil.jpg',
    filter:['SREA'],
    story:`So, my object is White Flower dầu gió (analgesic remedy lit: wind oil), it is equivalent to Tiger Balm and Vicks. So, when I was younger, I was a child, I used it for everything. If I was ill or had a headache, my mum would rub it on my temple. If I had the flu my she would scrape it on my back (in a technique known as cạo gió, 刮痧, lit: scrape the wind). It’s a Tiger Balm but the liquid version, it’s just growing up I’ve always used it for everything.

So now I have it in my house, again, I use it for everything. If my kids need it, if they have a bellyache, I’ll rub it on their stomach, if…anything really. If they have a little bit of pain, I just say: “Oh just grab the Tiger Balm”, Tiger Balm is not the proper name, but that’s what we call it at home. Or if they’ve got the flu, I put a few drops in their baths. It’s just something, I don’t know if it works, or if you are supposed to use it for it. My kids think it works as they will ask for it. They will say: “Where’s the Tiger Balm?” Or if someone has a cold, we use it like Vicks. So, when my youngest son, when he was a baby, he had a cold, we would put it on his chest. I have to make sure everybody has washed their hands after using it.

We also have, the actual Tiger Balm at home, but we also got this, White Flower dầu gió. We used to stock up on Tiger Balm, but now Boots and Holland & Barrett have it, we don’t bother anymore.

I think it is just a culture thing, it’s something I’ve always done. It’s like chopsticks. I’ve used it since I was young, it’s something I am familiar with. I think it is psychological. Sometimes I put it on a mosquito bite. It’s a little bottle of magic.

Đồ vật của tôi là dầu bạch hoa, nó tương tự với dầu con hổ dưỡng hay Vicks. Khi tôi trẻ hơn bây giờ, tôi còn là một đứa trẻ, tôi đã sử dụng nó cho mọi thứ. Nếu tôi bị ốm hoặc đau đầu, mẹ tôi sẽ bôi nó lên hai thái dương của tôi. Nếu tôi bị cúm, cô ấy sẽ cạo nó trên lưng (theo một kỹ thuật được gọi là cạo gió, 刮痧). Nó là dầu con hổ nhưng có dạng lỏng và trong suốt quá trình trưởng thành, tôi đã luôn dùng nó cho mọi thứ.

Bây giờ tôi vẫn có nó trong nhà và một lần nữa, tôi sử dụng nó cho tất cả mọi thứ. Nếu con tôi cần nó, nếu chúng bị đau bụng, tôi sẽ xoa nó lên bụng con, thực sự nếu như… có bất cứ điều gì. Nếu chúng hơi đau ở đâu đó, tôi chỉ cần nói lấy dầu con hổ đi. Hoặc nếu chúng bị cúm, tôi nhỏ vài giọt vào bồn tắm cho con. Nó chỉ là một cái gì đó, tôi thậm chí không biết nếu nó có 

hiệu quả không, hoặc nếu tôi có dùng nó đúng cách không. Con tôi nghĩ rằng nó hoạt động theo yêu cầu của chúng. Chúng nó sẽ nói: Dầu con hổ ở đâu? [Hay thậm chí vào một ngày khác, nửa kia của tôi, chồng, bạn đời của tôi, cái gì cũng được (cười), anh ấy đập tay vào cửa xe, ngay khi anh ta bước vào, anh ta hỏi dầu con hổ đó ở đâu. Vì vậy, cả nhà tôi sử dụng nó cho tất cả mọi thứ.] Hoặc nếu ai đó bị cảm lạnh, chúng tôi sử dụng nó như Vicks. Vì vậy, khi con trai út của tôi, Mason, khi nó còn nhỏ, nó bị cảm, chúng tôi sẽ bôi nó lên ngực con. Tôi phải đảm bảo mọi người đã rửa tay sau khi sử dụng nó.

Chúng tôi cũng có, dầu con hổ thực sự ở nhà, nhưng chúng tôi cũng có cái này, dầu bạch hoa. Chúng tôi đã từng dự trữ dầu con hổ, nhưng bây giờ Boots và Holland & Barrett đã có nó, chúng tôi không còn phải lo về điều đó nữa.

Tôi nghĩ đó chỉ là một thứ văn hóa, thứ gì đó mà tôi luôn luôn làm. Nó giống như đũa vậy. Tôi đã sử dụng nó từ khi còn trẻ, nó là thứ gì đó quen thuộc với tôi. Tôi nghĩ nó là tâm lý. Đôi khi tôi bôi nó lên một vết muỗi đốt. Nó có một chai ma thuật nhỏ.`
  },
  {
    id: 10,
    title:'A cooking implement to make bánh cuốn',
    name:'Anonymous',
    image:'cuon.jpg',
    filter:['SREA'],
    story:`This object is a cooking implement, to make bánh cuốn (Vietnamese steam rice rolls). I came from Vietnam, I left Vietnam when I was about four. I actually don’t remember anything about Vietnam, I have no impression of it. The only way I can relate back to Vietnam is through the food. And this is something is made, my mum makes it quite regularly, it’s sort of a home comfort type food. It’s quite difficult to make, as soon as I said to my mum, I wanted to make it, she bought out this cooking implement, and she taught me how to make it. But I still haven’t been able to make it successfully, yes, I am still trying.

As I am Chinese origin, but I’ve still grown up with Vietnamese food. So, my mum is Chinese, but we cook Vietnamese food, as well as Chinese food. But it’s just something I find that is quite hard to do, making this bánh cuốn. So, it’s something I want to learn, definitely! Otherwise when my mum isn’t here anymore, nobody is gonna able to make it.

So last year I decided I needed to learn how to make it, and I am forty something now (laughs), it never occurred to me to make it. I do like cooking and I think it is something I should learn to make. I do occasionally make Vietnamese food, like phở, I also make typical Chinese dinners, white rice, with small dishes of meats and vegetables too.

Đồ vật này là một công cụ nấu ăn, để làm bánh cuốn. Tôi đến từ Việt Nam, và rời Việt Nam khi tôi khoảng bốn tuổi. Tôi thực sự không nhớ gì về Việt Nam, tôi không có ấn tượng gì về nó cả. Thức ăn là thứ duy nhất tôi có thể liên hệ với Việt Nam. Và đây là một món phải tự làm và mẹ tôi làm món này khá thường xuyên. Bánh cuốn là một loại thực phẩm dễ ăn của mọi nhà nhưng nó rất khó làm. Ngay khi tôi nói với mẹ tôi rằng tôi muốn làm bánh cuốn, bà đã mua dụng cụ nấu ăn này và dạy tôi cách làm. Nhưng tôi vẫn chưa thể làm nó thành công, đúng vậy, tôi vẫn đang cố gắng.

Tôi là người gốc Hoa nhưng tôi vẫn lớn lên với đồ ăn Việt. Vì vậy, dù mẹ tôi là người Trung Quốc, nhưng chúng tôi nấu các món ăn Việt Nam cũng như các món ăn Trung Quốc. Nhưng chỉ món này là tôi thấy khá khó làm, bánh cuốn ấy. Thế nên, đây là thứ mà tôi muốn học, chắc chắn là vậy! Nếu không, khi mẹ tôi không còn ở đây nữa, không ai có thể làm được.

Do đó, năm ngoái tôi quyết định tôi cần học cách làm nó, và bây giờ tôi đã bốn mươi tuổi (cười), điều này chưa bao giờ xảy ra với tôi trước đây. Tôi thích nấu ăn và tôi nghĩ đây là thứ tôi nên học để làm. Thỉnh thoảng tôi cũng làm món ăn Việt Nam, như phở, và tôi cũng làm những bữa tối đặc trưng của người Hoa, cơm trắng, với những món ăn kèm như thịt và rau nữa.`
  },
  {
    id: 11,
    title:'Vietnamese English Dictionary',
    name:'Hung',
    image:'hung.jpg',
    filter:['SREA'],
    story:`I have been in the UK for 40 years and in this centre for 24 years. I was 19 when I left Vietnam. I am 54 now.
There were 34 people on the boat to Hong Kong. We escaped at night. We stayed in the refugee camp in Hong Kong for 3 months and then Britain accepted us. We landed in Heathrow and went to a town in the North near Bradford. We stayed there for 3 years and moved to London.
We left in a hurry at night, so I did not bring anything with me. I did not bring any photos, nowadays if we want to take photos we can just use our mobile phone. If we carried too many things, people might get suspicious and do stop and search. We would be in trouble if they know we illegally escaped. 
When I first came here I had difficulties. I did not know English, it was so difficult. I could not find a job. I had to do anything to find more work and to find money. I worked in Burger King, and then I worked in a factory, and a restaurant, then I worked in Hilton Hotel, cleaning. I couldn’t cope with that because cleaning the hotel was so difficult for me. I worked for a few years and fell ill, and the GP referred me to the Vietnamese Mental Health Service. 
I love learning English, I learnt it day by day using the dictionary. If I don’t understand a word I look it up in the dictionary. The first words I learnt after coming here were “teacher”, “chair”. In the first 10 years I missed Vietnam because I didn’t understand English and I missed my mother and sisters who were not here. We did not have enough money to pay the boat owner at that time for the whole family to come. 10 years later we applied for the family reunion, and my family came to the UK. I know English now, I don’t miss Vietnam now. 
[Pointing at the dictionary] “This is the word “happy”, happy life. In Vietnamese it’s sung sướng; hạnh phúc. Happy, “sung sướng” means “material”, and “hạnh phúc” means mental.”* Sometimes I wish I understood English fully, but I am happy now, I am “half English, half Vietnamese”. 
*Note: Verbatim of translation from Vietnamese into English for “sung sướng” is not material. sung sướng; hạnh phúc “Hạnh phúc” is not mental. Interpreting his speech, perhaps “sung sướng” can be inferred as “physical feeling”, you can touch and sense like material things, “hạnh phúc” can be read like an “emotional feeling”, something in your thought and mind like mental thinking.
Tôi đã ở Anh được 40 năm và ở trong trung tâm này được 24 năm. Tôi rời Việt Nam năm 19 tuổi. Còn bây giờ tôi 54.

Thuyền của tôi chở 34 người tới Hồng Kông. Chúng tôi chạy trốn trong đêm. Chúng tôi đã ở trại tị nạn tại Hồng Kông 3 tháng và sau đó Anh Quốc đã chấp nhận chúng tôi. Chúng tôi hạ cánh ở sân bay Heathrow rồi tới một thị trấn ở phía Bắc gần Bradford. Chúng tôi ở đó 3 tháng và sau đó chuyển tới London. 

Chúng tôi đã phải rời đi vội vã trong đêm nên tôi không mang thứ gì bên mình. Tôi không có bất cứ tấm ảnh nào. Bây giờ nếu chúng ta muốn chụp ảnh, chúng ta chỉ việc dùng điện thoại. Nếu chúng tôi mang quá nhiều thứ, người ta sẽ nghi ngờ và chặn lại kiểm tra. Nếu họ biết chúng tôi đang chạy trốn bất hợp pháp, chúng tôi sẽ gặp rắc rối.

Khi tôi mới đến đây, tôi gặp rất nhiều khó khăn. Tôi không biết tiếng Anh, nó rất khó. Tôi không thể tìm được việc. Tôi đã phải làm mọi thứ để kiếm thêm việc để có tiền. Tôi đã làm ở Burger King rồi tôi làm ở nhà máy, nhà hàng, sau đó làm dọn dẹp ở khách sạn Hilton. Tôi chịu không làm được công việc này vì dọn dẹp ở khách sạn quá khó với tôi. Tôi làm được vài năm thì bị ốm. GP đã giới thiệu tôi đến Dịch vụ Sức khỏe Tâm Lý dành cho người Việt.

Tôi thích học tiếng Anh, tôi học nó hằng ngày bằng cách sử dụng từ điển. Nếu tôi không biết một từ nào đó, tôi tra trong từ điển. Từ đầu tiên mà tôi học được khi đến đây là “giáo viên”, “ghế”. Trong 10 năm đầu tiên, tôi rất nhớ Việt Nam vì tôi không hiểu tiếng Anh, và tôi nhớ tới mẹ và chị em gái tôi vì họ đều không ở đây. Chúng tôi đã không có đủ tiền để trả cho chủ thuyền lúc đó để đưa cả gia đình sang. 10 năm sau, chúng tôi đăng ký để gia đình mình được hội tụ và cả nhà tôi đã sang được đây. Bây giờ tôi đã biết tiếng Anh và không nhớ Việt Nam nữa.

Đây là từ “hạnh phúc”, cuộc sống hạnh phúc. Tiếng Việt nó có nghĩa là “sung sướng”, “hạnh phúc”. “Sung sướng” là vật chất và “hạnh phúc” là tinh thần. Đôi khi tôi ước mình hiểu tiếng Anh hoàn toàn nhưng giờ thì tôi hạnh phúc, tô là người “nửa Anh nửa Việt”.`
  },
//   {
//     id: 12,
//     title:'Martial arts and wellbeing',
//     name:'Xuan',
//     image:'martialart.jpg',
//     filter:['SREA'],
//     story:`I was born in Vietnam. I left when I was 4. Born in 1973, when the war almost ended. 
// Object 1: Photo of Hong Kong
// Memory of Vietnam. I can only vaguely remember, it’s like a dream. I remember myself and my brother, being kept indoors, when my parents were working. We were locked inside the house. I had images of the house, of a fan, ceiling, maybe just images of trying to reach a shelf and things falling down, but then apart from 5 or 6 images, I don’t remember much when I was 4 years old. Then I remember the image of inside the boat, it was very dark, and then from then on, my parents said we spent 6 months in China, before going to Hong Kong. I got more memory of Hong Kong. This is when I was about 5 or 6 in Hong Kong, when we were in a refugee camp. My dad was working on a building site, my mum made Vietnamese pastries to sell on the street. My brother and I sat on the street and sold the pastry to the passers-by. The other thing was collecting Chinese manga magazines. They would pay like an equivalent of 1p or something like that. We did whatever we could to keep ourselves busy, but there was a curfew, we had to be back to the camp by 10 pm or something like that. We were classed as the boat people, refugees from Vietnam. It wasn’t unhappy. (1980)

// Object 2: Parent’s house
// My grandparents, my uncles and my family decided to come to the UK. We came in the winter, it was freezing cold, it was first time I saw snow. We were placed in a temporary housing in Southampton, but my parents didn’t like it. We asked to move to a place with more Asian families, so we requested to come to London. After 3 months, we moved to Islington. 1982. My parents still lived in the house we were in. I didn’t know much about Hackney at that time, probably in my 20s then I started to realise there were other communities in Lewisham, the docklands etc. 
// I feel very grateful for having the opportunity to move. I have been back to China, I have met some of my families in China, and they said they regretted staying in China, their children have never left China, and they have seen us coming back, and we have so much knowledge and understanding, have a little bit of wealth, got opportunity to travel, to see things, whereas their children were stuck in China.  I guess my British history starts in London, not in Southampton. Before that I was just like a parcel being carried by my father. 
// My home has always been my parent's place, when we first moved in Islington in London. Everything else was just temporary. I lost the Vietnamese language when I left at 4. We speak Cantonese at home. I have been back to China a few times, but not Vietnam. Home would be here, in London. 
// Object 3: Singapore noodles 
// I have never had a problem mixing with different types of people. it's only when I started my business with my father, I realised I guess, the catering business, will kill your social life, you stopped seeing your friends, seeing interesting people, all you think is your business, how to make it more efficient. I guess that period from 1995 for about 15 years, I was losing them. you started isolating yourself, you feel more vulnerable. the English people, the Black, the Asians, they become more foreign. When you run a Chinese catering business, you start to develop a distance. It was for my family, but it wasn't good for my mental health. I have experienced racism in my youth but it didn’t feel that strong. When I ran my own business, and I stopped seeing my friends, then you became more sensitive, any little racism, discrimination, you became more vulnerable, it affects you more, you feel like a target.
// Would I do it again? I would if it's for my family, if my family wants to do a business. But I wouldn't expect my children to give up what I had to give up.

// Object 4: Letter from first kungfu teacher 

// In my work in the bank, I have gone up to the managerial level. It was stressful and there was stress in my eye, and I was getting blackouts. I literally had a blackout, once a month. One time I had to go home, I must have blacked out in the office, a few times. So I said, something had to change. I gave up my job in the bank because it wasn't healthy for me, wasn't healthy for my relationship. 

// I don't want to slow down, I want to keep training, to keep my mind fresh, to be as I was when I was in my late 20s, 30s. When I was 15, I learnt martial arts in the youth club. I started going to the youth club when I was 8, or 9. They had funding to do sports, calligraphy. My teacher, still my teacher now. It was only when I was working full-time then I started to slow down. When I was working in the bank, I didn't do any training, and it was affecting my health, my mental health. I became very stressed, kind of lost in a way. So, in the past 3-4 years I have gone back into it, quite intensely. 

// Last year we were approached by Jabez, Jabez is my late father-in-law’s friend. Jabez has taken over running of the Chinese community centre in Hackney. He saw that there's an opportunity to move to An Viet house to do things, so he called us in to do a few projects with young people in Hackney. We saw that the An Viet house has a lot of potential to become a community centre whilst we can go in there, to do some events, to do some training, to do some festivals, events, not just martial arts, but also carnivals, festivals, to produce costumes, to apply for funding for the arts to do activities.
// `
//   },
  {
    id: 13,
    title:'A group photo in China',
    name:'Kim',
    image:'china.jpg',
    filter:['SREA'],
    story:`I was born after the Vietnam American war to a Chinese father and a Vietnamese mother and am also a first generation Vietnamese Political Refugee, yes one whose family escaped Vietnam on a boat! After the war, conflicts started between the Vietnamese and Chinese government thus the start of discrimination between the Vietnamese and Chinese citizens living in Vietnam. 
 
My parents married a few years before the war had ended. My father had 3 children above me from his ex-wife who had custody of one of my half-sister whom I had never met before. My father was a Merchant Captain and was often away at sea working a few weeks at a time and was not always home. My mother was a Seamstress so was always holding up the fort at home and bared all the brunt of discrimination flung her way for marrying a Chinese man. The police even asked her why she had married a Chinese man during such a political period. She never told us what her reply was, but I guess it was better not to provoke the authorities.  On top of this, she often had to put up with her sister in-law’s unreasonable behaviour (my father’s sister in-law {brothers wife}) whenever she sent my cousins over for meals. My aunt in-law was well known to be a feisty and rude bully who spent her money on luxuries instead of feeding her kids. That’s coffee every morning which at the time was a luxury under a hard core communist society.  At times when my mother was not able to feed all my  cousins (9 not including myself and siblings), my aunt had often scolded and swore at her in Chinese (Cantonese – my father’s dialect). At the time, my mother did not speak Chinese at all so she just ignored her. 

After I was born, I was often discriminated against by certain family members as well as some neighbours. My great aunt visited us once but only gave my older siblings gifts but not me as I was not pure Chinese and said to my mother to let her take care of my older siblings if my mum was not able to do so. Of course my mother did not let that happen as she promised my father she would bring up his kids like her own. 

On a couple of occasions, I was asked by a family member as well as a neighbour ‘your father is Chinese aren’t you going back to China?’ How was a child supposed to respond to that?  My mother having heard this so many times and from a close family member was very upset and that’s when she decided to leave Vietnam as a family and if we died at sea, at least we’ll all be together. The discrimination cut deep for my mother especially having to bear most of the brunt of it all. My parents knew that whether we lived in Vietnam or China, the situation would be the same with family and the authorities so they wanted to live in another country far away where my siblings and I could have a better life without discrimination, the bullying and out of the communist regime. 
 
My parents started to sell whatever they could for extra money to help us buy a space on the boat, however was careful not to let anyone know because if people were caught, they would have been thrown into jail although the authorities had indirectly told the Chinese they were welcome to leave, so turned a blind eye to the escapes. One neighbour knew of our plans and blacked mailed my father for money, so my father gave in. Later when we went back to Vietnam for the first time, this neighbour had no shame and even asked my father if he remembered him. How can you forget such a person?  

We left when I was 3 years old. I remembered that early morning we were due to leave, I was still sleepy and my mother’s cousin carried me down to the boat. When I woke up we were already at sea. I felt sea sick from my memories and staring out at the ocean with some blurry moments. It was like a dizzy dream that I was in. I often heard my parents talk to other refugee friends about their journey and how unlucky some boats were. Some boats sailed in the wrong direction and were met with pirates who robbed them, killed the men and raped the women, the typical criminal actions of pirates. My cousin in-laws landed on a Malaysian island and some people were found on a large rowing boat at sea. Luckily my father was familiar with the South China Sea from being a sailor, so our journey to Hong Kong was relatively smooth apart from one silly man who claimed to be able to drive a boat but almost crashed and got us all killed when my father took a break. My father was the main driver and was working day and night with help from his colleague who later lived with us. He was the man I knew as a grandfather. Both sets of my biological grandparents died before I was born. 

When we landed in Hong-Kong, I remembered being very scared and said to my mum ‘we shouldn’t’ have left home’. My mother had later joked about it, ‘if we hadn’t left you wouldn’t have had what you have now’. I would roll my eyes at her knowing this was true…  The Hong-Kong police and immigration personnel’s were not very nice and diplomatic during the 70s. They spoke to refugees like we were diseases and there were a lot of unpleasant situations inside the camp as well as outside. 
- One officer would go into the women’s shower area and told them to get out as time was up.
- Some people were asked to kneel in the sun as a form of punishment (grandfather was one of them) because they were fighting over an apple. It must have felt like a concentration camp.
- Immigration Officers had changed my first name even after my mum had shown them my birth certificate, god knows how she managed to keep that after such a journey. Another friend I know said they had changed his surname! I later had my name corrected. 
- I remembered my parents mentioning about a situation where some of the local Chinese Hong-Kong people wanted to buy children because they were not able to have any, so we were told. My parents too were approached but refused their offer. Who knows what these people really did to these kids after they were sold…
- Refugees were also discriminated against even in Hong-Kong. Some grocery stalls would not sell food to non-Chinese speakers. I heard this from family friends.  

 We spent a year in the refugee camp in the Sam Shui Bo area of Hong-Kong.  During this time, refugees were allowed to find employment so my father and cousin worked at a fishing company by the port. His employer was fond of him and often gave him fish to take home so we often had fish for dinner and sold some to neighbours. My mother made and sold sticky rice daily as well as did some babysitting. By the time Chinese New Year arrived (Vietnamese share the same festival period), my parents had money so wanted to buy me some new clothes and shoes. The tradition is for us to wear new things during the New Year. Upon asking for the price of shoes at a shoe shop, the owner questioned whether my father could afford them. This infuriated him and what came out of his mouth, I do not want to repeat. My new pair of shoes were stolen after visiting family friends on New Year’s Day, guess that’s why l love shoes now.  

My family arrived to the UK when I was about five. I have a memory of sitting on a plane and the whole plane was spinning around – that was my first experience of flying in an aeroplane, compliments of British Airways. When we arrived in England, I remember being collected and driven to our first British home in Wetherby. We lived temporary in a mansion that was surrounded by woodlands and managed by a priest, nuns and some other staff members and English teachers. It was a refuge housing refugees while we waited for a proper home.  The staff there were so warm and welcoming and involved us in the local customs and festivals. The kids were driven to school every morning in a minivan and during the summer we went blackberry picking.  
 
Later on we were settled in our own home in North Yorkshire where we lived for a few years. We experienced the real winter for the first time and met the ‘snow white!’ During those few years in our own home (which was 20 times bigger than our one big room in Vietnam), my parents were taught how to use a basket when shopping as most of refugees picked up items in the supermarkets and put them in their pockets and also because it was cold especially when walking by the frozen food sections. I remembered feeling sickly because of eating some jelly pieces. It turned out we were eating jelly blocks which should have been melted with water in order to make jelly. My parents thought they were confectionary and cut up the pieces to eat. We were country bumpkins in this new country (current term ‘fresh of the boat’)! 

I went to a nearby primary school and remembered the teachers were extremely friendly. My Head Mistress (what they were called back then), Mrs Peacock (funny how I still remember her name) looked fierce and strict and was always telling the Pakistani boys off for being naughty. One day she was so angry she pulled one boy’s trousers down and smacked his behind, but that never stopped his naughtiness. However, she was always nice to me and found my journey to the UK interesting but I wasn’t able to tell her my story back then. I had limited English and couldn’t remember much. In middle primary school (between the junior and senior primary school separated by a patch of grass – not sure why it was separated like that), it wasn’t so nice. I found some of the adults rather cold towards kids and some kids were unpleasant towards me. At lunch times, the Dinner Ladies would blow their whistles and shout Pakistani or English girls/boys and the kids would form 2 rows to go into the dinner hall for lunch. So there was myself and a Malaysian girl and we had to choose a queue to head to lunch. Now if you didn’t finish all your lunch, you couldn’t leave the hall. I was stuck eating old-fashioned, cold, English sandwiches, egg and cress because I refused to eat meat and was not allowed fish fingers. This put me off sandwiches until I was an adult, but even now sandwiches are not my first choice for lunch. Another thing which I hated until I attended secondary school were woolly garments. My mum was scared that I would freeze in the winter from the cold weather, so she knitted this awful god-forsaken suit, thick cardigan and trousers in multi-colours of blue which I had to wear. The wool was prickly and thick it made me itch all over.  On top of that, I had to wear a bright yellow or orange balaclava, this was later passed down to my brother. We must have looked like child burglars walking to school.

I have no idea why but was often bullied by a group of girls and the Pakistani boys, so I used to stand between my school and the senior school calling a friend (family friend’s kids) – he was older, bigger and in the Senior school. Bless him he always came running and it scared the bullies off.  I met my first bestie a Pakistani girl who lived a few doors down from me; we share the same birth date and year. It’s a shame we didn’t keep in touch. Whenever I went outside to play with my friends, some of the time was spent running away from dogs. These older girls and some girls from school would send their dogs chasing me down the street back home. It was like Forest Gump only difference was running away out of fright. Ever since then, I was scared of dogs and furry animals but I think it made me a fast runner for my size – I was one of the smallest in my class. 

My parents decided to move to London because the Asian community where we lived was tiny. I think we only knew up to 8 families in that town plus it was difficult finding translators when one was needed, I was my family’s little translator. I was 9 years old when we arrived in London and lived with relatives for a while before moving into a family run hostel while we waited to be housed. I hated my school years as I was often bullied at school. I was quite competitive and sporty and was often made to race with other class members during PE class. I used to either win or was equal with the boys and I think that’s when the bullying started. I think my teachers must have enjoyed watching me win and kept asking the class to race against each other. The bullying got really bad, one particular bully and his friends caught up with me outside school one day and punched me. My headmaster was furious, I’m not sure what he did, but it did stop the physical abuse. I later heard this boy joined the army. 

During my years at secondary school, I was often tormented by one girl who later earned a nick name ‘Batty Bola’ given by the teachers. I hated the 5 years of being there, my grades were not brilliant until l was at college. Most of the time I felt that my head was always in the clouds, not understanding anything. I now think, maybe my classmates had suffered some kind of abuse at home which could explain why they were so cruel at school, but who knows?… On top of the usual 5 days of school, I was sent to Chinese school on both Saturdays and Sundays and I hated it because I felt that I never had a rest. I just wanted to go out and play. But my dad wanted my brother and me to be able to speak our own language. We never went to Vietnamese school because the only classes available were at some Catholic church and we were not Catholics so could not attend. It was confusing enough having to speak 3 languages at that age, so it was a mixture of using both Vietnamese and Chinese words to communicate with my parents. 

Growing up was rather frustrating and confusing as my mum was quite strict and controlling. I was taught about my culture but my parents never told me which culture aspects belong to which race, so this started the identity confusion game. For example, I was always taught that girls should never eat food on the streets but had no idea which culture it was from so assumed it was from both – not sure what happened to the next generation. Till this day, I still snack on the streets and don’t care anymore. I’m just exercising my freedom and partly the rebel in me.  

My parents ensured I went straight home after school or else this would warrant a search party and almost the police at one point. I wanted to have fun like other kids, couldn’t understand why I had to do dishes but my friends didn’t have to do it. I was never allowed to join in with after school activities unless these were extra lessons so I had to give up playing in the school Steel band which I really enjoyed. However my brother was allowed to do all these things because he was a male.  So during college field trips I would be out every night partying hard because I knew that I would get shouted at if I tried to do this back in London. Later on I pushed the boundaries and told my controlling parents it’s embarrassing having to tell people at my age that I am not allowed out. They slowly accepted this, but it did take a long time. My parents over protectiveness did no justice for my confidence either. I later worked at Forensic Science and after having being exposed to some criminal cases, I understood perhaps why my parents worried so much about me as a female.

A question I used to get stuck on was ‘what’s your nationality? Or where are you from’ I felt like I had to tell a long story of where I was born, why I am not fluent in both these languages as much as I would like to be. This happened during one of my earlier trips visiting friends in Hong-Kong where I needed medical attention and was taken to a local hospital. The reception staff and Dr instead of attending to me, asked about my name (Chinese surname) after I had shown them my passport and why I spoke good Chinese. My pain by then had subsided and I was able to spend 5 minutes telling them about my background. Now I would just say I’m Vietnamese Chinese.

After I graduated, my whole family went back to Vietnam to visit for the first time. My mum’s relatives were welcoming and cousins who were closed to her were extremely happy to see her and meet us. We went back to my mum’s village to see her sister and this was both an emotional and a shocking event…let me elaborate. My mum and her sister had been separated as children both being adopted by different families, they were Orphans and had not seen each other for more than 20 years after my mum left Vietnam. So it all came out in tears, they just hugged each other. The shocking part for me and my brother was when we stepped outside my Great Aunts house, we were greeted by half the villagers just standing there staring at us. We looked at each other, then looked at the villagers and we turned around and walked straight back into the house. This reminded me of a scene from the film ‘Heaven and Earth’ starring Tommy Lee Curtis, a war Veteran whose wife took her kids back to Vietnam to visit the family. Back in the city, the locals couldn’t work out where my brother and I were from, they thought we were from other parts of Asia visiting Vietnam.  They didn’t believe me when I told them that we were Vietnamese. 

After a few years of working in the adult world, I joined part-time courses and learnt new things. It was an opportunity to stay out after work because being at home and under pressure from my parents to get married was upsetting. I also felt I didn’t have much knowledge any anything about the world, it felt like a waste of time. So I joined a Chinese Mandarin class at a university near my office and later went to China for a year as I was given part scholarship. When I told my parents this, we had a huge argument as they didn’t want me to leave home and especially go to a communist country. Some family friends were asking why I would go there and seemed to look down on me for doing this. Yet later on, those same family friend’s children went to live and worked in China. 
My year in China was very interesting and I wished I had kept a journal, this was one of the happiest memories and best years of my life so far. I was 25, free from my controlling parents, even though I had to share a room with another student, but I was carefree; my roommate was nice, I didn’t need many possessions and loved the adventure I had. However, it wasn’t easy at the start, in fact I cried the first night I was there especially after having been shown where the student toilets and showers were. The toilet and shower cubicles were right next to each other and the toilets were a hole in the ground! However they were kept very clean. After having spoken to some students from Europe, they told me they too had cried the first night they arrived at the dormitory. Whether it was a girl or guy, we had no shame in sharing this bit of information because we all cried for the same reason – the hole in the ground toilets! Some older flats in China still have these types of toilets.  To me, squatting is a physical art form, you need super strong thigh muscles. This reminded me of a film (can’t remember the name) starring Chow Yun Fat who always took a stool into the toilets and I realised why now, I’ll leave that to your imagination. After exploring the city of Nanjing (which was where I was based), toilets in the student accommodation were luxury. Never in my life had I seen such horrendous public toilets, the worst were at train stations, very dirty! Some places do not even have cubicles! The public toilet situation (not the actual toilet) in China was shown on a programme called ‘An Idiot Abroad’ starring Karl Pilkington. The programme also travels around the world and great to watch if you like learning about other countries. So that was the first shock to my system.

Aside from the toilet issue, the start of my year in China was also upsetting due to the fact that I was basically insulted about not being able to speak Mandarin Chinese even though Cantonese is a Chinese dialect. Every time I told someone I was from the UK, the first thing they said was ‘you must be rich’. Their perception about the British was that we were rich because that was how British are shown on TV in China, however these people had never been abroad. This is of course due to no fault of their own as this is what the media stereotyped the Western world to be like. However it did upset me especially when I said I am Chinese, their replies were, ‘but you don’t speak Chinese’ and if I said I am British, they said I didn’t look British. I eventually settled on using my Vietnamese race and it worked wonders. The locals seemed to like that so I continued to tell people I was Vietnamese and to avoid a long explanation. I began to enjoy my student life more and saw many interesting things and learnt more about the Chinese culture and found that there are slight culture differences from one region to another especially as China has more than 50 minorities and dialects. Such as, in the North, they don’t pick up their bowls to eat so their heads are bobbing up and down while pushing the food from the bowls into their mouths but Southerners we pick up our bowls to eat. During New Year different dishes are made depending on which region you are from. For the Vietnamese we make rice cakes filled with lentils and pork wrapped in leaves, my parents use banana leaves. This is the same for Southern Chinese people mainly the region bordering Vietnam (my dad’s region). This is how I have always known it to be. However Southern places like Hong-Kong don’t make rice cakes, they make a different type of rice cake which is smaller during the Dragon Boat festival. The one dish that everyone has during New Year is Nian Gao – dessert made from glutinous rice cake which has a chewy texture and something I like to eat too, unfortunately I can’t make it. My parents think it is bad luck if you are unsuccessful at making it – I don’t believe that.

An interesting conversation I had in class asked by one of my teachers was, ‘what do the people in the West usually write for a dating advertisement?’ I told her we would write about our personality and what type of person we would like to meet. However in China and most parts of Asia (might be different now), they would state what they have i.e. a job, a car, a house etc… My teachers were curious as to why I didn’t have a boyfriend as I guess at 25 my shelf life would be over soon had I lived in Asia. My reply was, I didn’t come to China to find a husband.  Life is just too short to be spending so much time searching for a man. We had a good discussion in my then basic Mandarin.  

My year abroad had been invaluable, the experience had boasted my confidence a great deal; I made a bunch of good friends; had explored some of the famous sights of China and had tasted different regional cuisines and in addition managed to remember some history while on tour. Back in Chinese school, it just went over my head. China is an amazingly beautiful country, rich in culture and for those wishing to visit China at some point in their lives, do get some squatting practice in because I know the countryside still have holes in the ground toilets, people out in the country can’t always afford such luxury. If a hole in the ground meets your basic needs, then so be it. Through my years of being able to travel to other countries, a hole in the ground toilets still exists in other western countries. Though China wasn’t the first country where I had seen these toilets, it was the thought of having to use it for a year freaked me out. The whole experience had also helped me understand some cultural differences and behaviours between both Vietnamese and Chinese. 

I am a proud first generation Vietnamese refugee and have had a long journey with discriminating experiences from birth and having to flee to a country for freedom yet still I can’t escape discrimination even though I live in a multi-cultural city. Certain situations will cause discrimination to rear backwards and this is the reality, the Brexit situation has proven this. I feel proud that my family have made it this far and survived. 

I have lived in the UK for 39 years, this is where I feel at home, it is my home.
`
  },
  
];// append each image with the directory

stories.forEach((s) => {
  if(s.image) s.image = requireImage(s.image);
});

export default {
  stories,
  description,
};
